---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
  labels:
    type: local
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: standard
  capacity:
    storage: 10G
  hostPath:
    path: /home/maverickram220/8am_definition/volumes
...
