---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: wordpress-rs
  namespace: test-ns
  labels:
    type: webapp
    author: intelliqit
spec:
  replicas: 3
  selector:
    matchLabels:
      type: webapp
  template:
    metadata:
      name: wordpress-pod
      labels:
        type: webapp
    spec:
     containers:
       - name: mywordpress
         image: wordpress
         ports:
           - containerPort: 80
             hostPort: 8080
...




